[package]
name = "ere-test-sp1-zkvm-interface-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
ere-platform-sp1 = { path = "../../../crates/platform/sp1" }
ere-util-test = { path = "../../../crates/util/test" }

[patch.crates-io]
sp1-lib = { git = "https://github.com/han0110/sp1", rev = "b4f72fe1de5d6d26b3d3f531fcabd137b03e3338" }

[patch."https://github.com/succinctlabs/sp1"]
sp1-lib = { git = "https://github.com/han0110/sp1", rev = "b4f72fe1de5d6d26b3d3f531fcabd137b03e3338" }
sp1-primitives = { git = "https://github.com/han0110/sp1", rev = "b4f72fe1de5d6d26b3d3f531fcabd137b03e3338" }
sp1-zkvm = { git = "https://github.com/han0110/sp1", rev = "b4f72fe1de5d6d26b3d3f531fcabd137b03e3338" }
libzkevm = { git = "https://github.com/han0110/sp1", rev = "b4f72fe1de5d6d26b3d3f531fcabd137b03e3338" }
