[package]
name = "ere-jolt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zkvm-interface = { workspace = true }
jolt-sdk = { git = "https://github.com/a16z/jolt", rev = "55b9830", features = ["host"] }
jolt-core = { git = "https://github.com/a16z/jolt", rev = "55b9830", features = ["host"] }
jolt = { git = "https://github.com/a16z/jolt", rev = "55b9830", features = ["host"] }
common = { git = "https://github.com/a16z/jolt", rev = "55b9830" }
thiserror = "2"
toml = "0.8"
ark-serialize = { version = "0.5.0", features = ["derive"] }
tempfile = "3.3"

[build-dependencies]
build-utils = { workspace = true }

[lints]
workspace = true
