[package]
name = "ere-io-serde"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bincode = { workspace = true, features = ["alloc", "serde"] }
serde.workspace = true

[dev-dependencies]

[lints]
workspace = true
