[package]
edition.workspace = true
license.workspace = true
name = "ere-dockerized"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bincode = "1.3"
clap.workspace = true
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.3"
toml.workspace = true
tracing.workspace = true
cargo_metadata = "0.19"

zkvm-interface = { workspace = true }

# Needed for customized serde.
risc0-zkvm = { version = "^2.3.0", default-features = false }
bytemuck = "1.13"

[dev-dependencies]

[build-dependencies]
build-utils = { workspace = true }

[lints]
workspace = true

[features]
default = []
