ARG BASE_IMAGE=ere-base:latest

FROM $BASE_IMAGE

# Install binutils for objcopy
RUN apt-get update && apt-get install -y --no-install-recommends \
    binutils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set default toolchain to nightly-2026-02-10
RUN rustup default nightly-2026-02-10

CMD ["/bin/bash"]
