// This file is @generated by prost-build.
/// Standardized error response
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorResponse {
    /// Error code
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    /// Human-readable error message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemStatusRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusInfoRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobsListRequest {
    #[prost(bool, tag = "1")]
    pub active_only: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkersListRequest {
    #[prost(bool, tag = "1")]
    pub available_only: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LaunchProofRequest {
    #[prost(string, tag = "1")]
    pub data_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub compute_capacity: u32,
    #[prost(uint32, tag = "3")]
    pub minimal_compute_capacity: u32,
    #[prost(enumeration = "InputMode", tag = "4")]
    pub inputs_mode: i32,
    #[prost(string, optional, tag = "5")]
    pub inputs_uri: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "HintsMode", tag = "6")]
    pub hints_mode: i32,
    #[prost(string, optional, tag = "7")]
    pub hints_uri: ::core::option::Option<::prost::alloc::string::String>,
    /// If set, indicates this is a simulated worker
    #[prost(uint32, optional, tag = "8")]
    pub simulated_node: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "9")]
    pub input_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckResponse {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemStatusResponse {
    #[prost(oneof = "system_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<system_status_response::Result>,
}
/// Nested message and enum types in `SystemStatusResponse`.
pub mod system_status_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Status(super::SystemStatus),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemStatus {
    #[prost(uint32, tag = "1")]
    pub total_workers: u32,
    #[prost(uint32, tag = "2")]
    pub compute_capacity: u32,
    #[prost(uint32, tag = "3")]
    pub idle_workers: u32,
    #[prost(uint32, tag = "4")]
    pub busy_workers: u32,
    #[prost(uint32, tag = "5")]
    pub active_jobs: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StatusInfoResponse {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub uptime_seconds: u64,
    #[prost(message, optional, tag = "4")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub metrics: ::core::option::Option<Metrics>,
}
/// Metrics information
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metrics {
    #[prost(uint32, tag = "1")]
    pub active_connections: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobsListResponse {
    #[prost(oneof = "jobs_list_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<jobs_list_response::Result>,
}
/// Nested message and enum types in `JobsListResponse`.
pub mod jobs_list_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// Success case
        #[prost(message, tag = "1")]
        JobsList(super::JobsList),
        /// Error case (e.g., system unavailable)
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JobsList {
    #[prost(message, repeated, tag = "1")]
    pub jobs: ::prost::alloc::vec::Vec<JobStatus>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusResponse {
    #[prost(oneof = "job_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<job_status_response::Result>,
}
/// Nested message and enum types in `JobStatusResponse`.
pub mod job_status_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        /// Success case
        #[prost(message, tag = "1")]
        Job(super::JobStatus),
        /// Error case (e.g., job not found)
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatus {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub data_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub phase: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub assigned_workers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(uint64, tag = "6")]
    pub start_time: u64,
    #[prost(uint64, tag = "7")]
    pub duration_ms: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkersListResponse {
    #[prost(oneof = "workers_list_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<workers_list_response::Result>,
}
/// Nested message and enum types in `WorkersListResponse`.
pub mod workers_list_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        WorkersList(super::WorkersList),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkersList {
    #[prost(message, repeated, tag = "1")]
    pub workers: ::prost::alloc::vec::Vec<WorkerInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkerInfo {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub compute_capacity: ::core::option::Option<ComputeCapacity>,
    #[prost(message, optional, tag = "4")]
    pub connected_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub last_heartbeat: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LaunchProofResponse {
    #[prost(oneof = "launch_proof_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<launch_proof_response::Result>,
}
/// Nested message and enum types in `LaunchProofResponse`.
pub mod launch_proof_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(string, tag = "1")]
        JobId(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeToProofRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProofStatusUpdate {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ProofStatusType", tag = "2")]
    pub status: i32,
    #[prost(message, optional, tag = "3")]
    pub final_proof: ::core::option::Option<FinalProof>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<ErrorResponse>,
    #[prost(uint64, tag = "5")]
    pub duration_ms: u64,
}
/// Messages from coordinator to worker
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CoordinatorMessage {
    #[prost(oneof = "coordinator_message::Payload", tags = "1, 2, 3, 4, 5, 6")]
    pub payload: ::core::option::Option<coordinator_message::Payload>,
}
/// Nested message and enum types in `CoordinatorMessage`.
pub mod coordinator_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Heartbeat(super::Heartbeat),
        #[prost(message, tag = "2")]
        Shutdown(super::Shutdown),
        #[prost(message, tag = "3")]
        RegisterResponse(super::WorkerRegisterResponse),
        #[prost(message, tag = "4")]
        ExecuteTask(super::ExecuteTaskRequest),
        #[prost(message, tag = "5")]
        JobCancelled(super::JobCancelled),
        #[prost(message, tag = "6")]
        StreamData(super::StreamData),
    }
}
/// Messages from worker to coordinator
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkerMessage {
    #[prost(oneof = "worker_message::Payload", tags = "1, 2, 3, 4, 5")]
    pub payload: ::core::option::Option<worker_message::Payload>,
}
/// Nested message and enum types in `WorkerMessage`.
pub mod worker_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        HeartbeatAck(super::HeartbeatAck),
        #[prost(message, tag = "2")]
        Error(super::WorkerError),
        #[prost(message, tag = "3")]
        Register(super::WorkerRegisterRequest),
        #[prost(message, tag = "4")]
        Reconnect(super::WorkerReconnectRequest),
        #[prost(message, tag = "5")]
        ExecuteTaskResponse(super::ExecuteTaskResponse),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Heartbeat {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatAck {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Shutdown {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub grace_period_seconds: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkerRegisterRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Maximum compute capacity of a node/cluster
    #[prost(message, optional, tag = "2")]
    pub compute_capacity: ::core::option::Option<ComputeCapacity>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkerReconnectRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    /// Maximum compute capacity of a node/cluster
    #[prost(message, optional, tag = "2")]
    pub compute_capacity: ::core::option::Option<ComputeCapacity>,
    #[prost(string, tag = "3")]
    pub last_known_job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkerRegisterResponse {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub accepted: bool,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub registered_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteTaskRequest {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskType", tag = "3")]
    pub task_type: i32,
    #[prost(oneof = "execute_task_request::Params", tags = "4, 5, 6")]
    pub params: ::core::option::Option<execute_task_request::Params>,
}
/// Nested message and enum types in `ExecuteTaskRequest`.
pub mod execute_task_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Params {
        #[prost(message, tag = "4")]
        ContributionParams(super::ContributionParams),
        #[prost(message, tag = "5")]
        ProveParams(super::ProveParams),
        #[prost(message, tag = "6")]
        AggParams(super::AggParams),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ContributionParams {
    #[prost(string, tag = "1")]
    pub data_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub hints_path: ::core::option::Option<::prost::alloc::string::String>,
    /// Indicates whether hints will be streamed
    #[prost(bool, tag = "5")]
    pub hints_stream: bool,
    #[prost(uint32, tag = "6")]
    pub rank_id: u32,
    #[prost(uint32, tag = "7")]
    pub total_workers: u32,
    #[prost(uint32, repeated, tag = "8")]
    pub worker_allocation: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "9")]
    pub job_compute_units: u32,
    #[prost(oneof = "contribution_params::InputSource", tags = "2, 3")]
    pub input_source: ::core::option::Option<contribution_params::InputSource>,
}
/// Nested message and enum types in `ContributionParams`.
pub mod contribution_params {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum InputSource {
        #[prost(string, tag = "2")]
        InputPath(::prost::alloc::string::String),
        #[prost(bytes, tag = "3")]
        InputData(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveParams {
    #[prost(message, repeated, tag = "1")]
    pub challenges: ::prost::alloc::vec::Vec<Challenges>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AggParams {
    #[prost(message, optional, tag = "1")]
    pub agg_proofs: ::core::option::Option<ProofList>,
    #[prost(bool, tag = "2")]
    pub last_proof: bool,
    #[prost(bool, tag = "3")]
    pub final_proof: bool,
    #[prost(bool, tag = "4")]
    pub compressed: bool,
}
/// Streaming messages for data transfer
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamData {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "StreamType", tag = "2")]
    pub stream_type: i32,
    #[prost(message, optional, tag = "3")]
    pub payload: ::core::option::Option<StreamPayload>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamPayload {
    #[prost(uint32, tag = "3")]
    pub sequence_number: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteTaskResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskType", tag = "3")]
    pub task_type: i32,
    #[prost(bool, tag = "4")]
    pub success: bool,
    /// Optional error message if success is false
    #[prost(string, tag = "5")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(oneof = "execute_task_response::ResultData", tags = "6, 7, 8")]
    pub result_data: ::core::option::Option<execute_task_response::ResultData>,
}
/// Nested message and enum types in `ExecuteTaskResponse`.
pub mod execute_task_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResultData {
        #[prost(message, tag = "6")]
        Challenges(super::ChallengesList),
        #[prost(message, tag = "7")]
        Proofs(super::ProofList),
        #[prost(message, tag = "8")]
        FinalProof(super::FinalProof),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WitnessExecInfo {
    #[prost(float, tag = "1")]
    pub witness_time: f32,
    #[prost(uint64, repeated, tag = "2")]
    pub publics: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "3")]
    pub proof_values: ::prost::alloc::vec::Vec<u64>,
    #[prost(string, tag = "4")]
    pub summary_info: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AsmExecuteInfo {
    #[prost(float, tag = "1")]
    pub time: f32,
    #[prost(float, tag = "2")]
    pub mhz: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZiskExecuteTime {
    #[prost(float, tag = "1")]
    pub total_duration: f32,
    #[prost(float, tag = "2")]
    pub execution_duration: f32,
    #[prost(float, tag = "3")]
    pub count_and_plan_duration: f32,
    #[prost(float, tag = "4")]
    pub count_and_plan_mo_duration: f32,
    #[prost(message, optional, tag = "5")]
    pub asm_execution_duration: ::core::option::Option<AsmExecuteInfo>,
    /// Time when task was received by worker (in milliseconds since UNIX epoch)
    #[prost(double, tag = "6")]
    pub task_received_time: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChallengesList {
    #[prost(message, repeated, tag = "1")]
    pub challenges: ::prost::alloc::vec::Vec<Challenges>,
    #[prost(message, optional, tag = "2")]
    pub witness_info: ::core::option::Option<WitnessExecInfo>,
    #[prost(message, optional, tag = "3")]
    pub zisk_execution_time: ::core::option::Option<ZiskExecuteTime>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Challenges {
    #[prost(uint32, tag = "1")]
    pub worker_index: u32,
    #[prost(uint32, tag = "2")]
    pub airgroup_id: u32,
    #[prost(uint64, repeated, tag = "3")]
    pub challenge: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProofList {
    #[prost(message, repeated, tag = "1")]
    pub proofs: ::prost::alloc::vec::Vec<Proof>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Proof {
    #[prost(uint32, tag = "1")]
    pub worker_idx: u32,
    #[prost(uint64, tag = "2")]
    pub airgroup_id: u64,
    #[prost(uint64, repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalProof {
    #[prost(uint64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag = "2")]
    pub executed_steps: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkerError {
    #[prost(string, tag = "1")]
    pub worker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ComputeCapacity {
    #[prost(uint32, tag = "1")]
    pub compute_units: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobCancelled {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InputMode {
    /// No input provided
    None = 0,
    /// Input will be provided as a PATH
    Path = 1,
    /// Input data will be sent directly
    Data = 2,
}
impl InputMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "INPUT_MODE_NONE",
            Self::Path => "INPUT_MODE_PATH",
            Self::Data => "INPUT_MODE_DATA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INPUT_MODE_NONE" => Some(Self::None),
            "INPUT_MODE_PATH" => Some(Self::Path),
            "INPUT_MODE_DATA" => Some(Self::Data),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HintsMode {
    /// No hints provided
    None = 0,
    /// Hints will be provided as a PATH
    Path = 1,
    /// Hints will be sent as a stream
    Stream = 2,
}
impl HintsMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "HINTS_MODE_NONE",
            Self::Path => "HINTS_MODE_PATH",
            Self::Stream => "HINTS_MODE_STREAM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HINTS_MODE_NONE" => Some(Self::None),
            "HINTS_MODE_PATH" => Some(Self::Path),
            "HINTS_MODE_STREAM" => Some(Self::Stream),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProofStatusType {
    ProofStatusCompleted = 0,
    ProofStatusFailed = 1,
}
impl ProofStatusType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ProofStatusCompleted => "PROOF_STATUS_COMPLETED",
            Self::ProofStatusFailed => "PROOF_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROOF_STATUS_COMPLETED" => Some(Self::ProofStatusCompleted),
            "PROOF_STATUS_FAILED" => Some(Self::ProofStatusFailed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskType {
    PartialContribution = 0,
    Prove = 1,
    Aggregate = 2,
}
impl TaskType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PartialContribution => "PARTIAL_CONTRIBUTION",
            Self::Prove => "PROVE",
            Self::Aggregate => "AGGREGATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PARTIAL_CONTRIBUTION" => Some(Self::PartialContribution),
            "PROVE" => Some(Self::Prove),
            "AGGREGATE" => Some(Self::Aggregate),
            _ => None,
        }
    }
}
/// Stream type enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StreamType {
    Start = 0,
    Data = 1,
    End = 2,
}
impl StreamType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Start => "STREAM_TYPE_START",
            Self::Data => "STREAM_TYPE_DATA",
            Self::End => "STREAM_TYPE_END",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STREAM_TYPE_START" => Some(Self::Start),
            "STREAM_TYPE_DATA" => Some(Self::Data),
            "STREAM_TYPE_END" => Some(Self::End),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod zisk_distributed_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ZiskDistributedApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ZiskDistributedApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ZiskDistributedApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ZiskDistributedApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ZiskDistributedApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Bidirectional stream between worker(s) and coordinator
        pub async fn worker_stream(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::WorkerMessage>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CoordinatorMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/WorkerStream",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "WorkerStream",
                    ),
                );
            self.inner.streaming(req, path, codec).await
        }
        /// Admin endpoints (optional, for monitoring)
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthCheckRequest>,
        ) -> std::result::Result<
            tonic::Response<super::HealthCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "HealthCheck",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn system_status(
            &mut self,
            request: impl tonic::IntoRequest<super::SystemStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SystemStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/SystemStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "SystemStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn status_info(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StatusInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/StatusInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "StatusInfo",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn jobs_list(
            &mut self,
            request: impl tonic::IntoRequest<super::JobsListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JobsListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/JobsList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "JobsList",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn job_status(
            &mut self,
            request: impl tonic::IntoRequest<super::JobStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JobStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/JobStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "JobStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn workers_list(
            &mut self,
            request: impl tonic::IntoRequest<super::WorkersListRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WorkersListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/WorkersList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "WorkersList",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Coordinator control
        pub async fn launch_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::LaunchProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LaunchProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/LaunchProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "LaunchProof",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Client subscription to job completion
        pub async fn subscribe_to_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeToProofRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ProofStatusUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/SubscribeToProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "SubscribeToProof",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
