// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CostPerType {
    #[prost(uint64, tag = "1")]
    pub main: u64,
    #[prost(uint64, tag = "2")]
    pub opcode: u64,
    #[prost(uint64, tag = "3")]
    pub memory: u64,
    #[prost(uint64, tag = "4")]
    pub precompile: u64,
    #[prost(uint64, tag = "5")]
    pub tables: u64,
    #[prost(uint64, tag = "6")]
    pub other: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecutionStats {
    #[prost(uint64, tag = "1")]
    pub steps: u64,
    #[prost(uint64, tag = "2")]
    pub duration_nanos: u64,
    #[prost(message, optional, tag = "3")]
    pub cost_per_type: ::core::option::Option<CostPerType>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InputChunk {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InputKind {
    #[prost(oneof = "input_kind::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<input_kind::Kind>,
}
/// Nested message and enum types in `InputKind`.
pub mod input_kind {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        /// first chunk; use PushJobInput for additional chunks
        #[prost(message, tag = "1")]
        Inline(super::InputChunk),
        /// file:// unix:// quic://
        #[prost(string, tag = "2")]
        StreamUri(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Proof {
    /// UUID
    #[prost(string, tag = "1")]
    pub proof_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub hash_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub verification_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ProofKind", tag = "4")]
    pub proof_kind: i32,
    #[prost(bytes = "vec", tag = "5")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub public_inputs: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "7")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub completed_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// RPC-level error — returned in Status details for programmatic inspection.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApiError {
    /// stable numeric code (see error table)
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// e.g. "JOB_NOT_FOUND"
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// human-readable detail
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Job-level failure (the job ran but did not complete successfully).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFailure {
    #[prost(oneof = "job_failure::Kind", tags = "1, 2, 3, 4, 5")]
    pub kind: ::core::option::Option<job_failure::Kind>,
}
/// Nested message and enum types in `JobFailure`.
pub mod job_failure {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Timeout(super::JobFailureTimeout),
        #[prost(message, tag = "2")]
        Input(super::JobFailureInput),
        #[prost(message, tag = "3")]
        Execution(super::JobFailureExecution),
        #[prost(message, tag = "4")]
        Internal(super::JobFailureInternal),
        #[prost(message, tag = "5")]
        Cancelled(super::JobFailureCancelled),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFailureTimeout {
    #[prost(enumeration = "JobPhase", optional, tag = "1")]
    pub phase: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "2")]
    pub limit: ::core::option::Option<::prost_types::Duration>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFailureInput {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFailureExecution {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFailureInternal {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobFailureCancelled {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterGuestProgramRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub zisk_elf: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterGuestProgramResponse {
    /// blake3 content hash of zisk_elf
    #[prost(string, tag = "1")]
    pub hash_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobRequestMessage {
    #[prost(message, optional, tag = "1")]
    pub job_kind: ::core::option::Option<JobKind>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobResponse {
    /// UUID
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobKind {
    #[prost(oneof = "job_kind::Kind", tags = "1, 2, 3, 5")]
    pub kind: ::core::option::Option<job_kind::Kind>,
}
/// Nested message and enum types in `JobKind`.
pub mod job_kind {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Setup(super::SetupRequest),
        #[prost(message, tag = "2")]
        Prove(super::ProveRequest),
        #[prost(message, tag = "3")]
        Wrap(super::WrapRequest),
        /// AggregateRequest aggregate = 4; // TODO: not yet defined
        #[prost(message, tag = "5")]
        Execute(super::ExecuteRequest),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetupRequest {
    #[prost(string, tag = "1")]
    pub hash_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub with_hints: bool,
    #[prost(string, tag = "3")]
    pub program_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetupResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub vk: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProveRequest {
    #[prost(string, tag = "1")]
    pub hash_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub input: ::core::option::Option<InputKind>,
    #[prost(message, optional, tag = "3")]
    pub proof_timeout: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "ProofKind", tag = "4")]
    pub proof_dest: i32,
    #[prost(message, optional, tag = "5")]
    pub hints: ::core::option::Option<InputKind>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProveResponse {
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<Proof>,
    #[prost(message, optional, tag = "2")]
    pub stats: ::core::option::Option<ExecutionStats>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WrapRequest {
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<Proof>,
    #[prost(enumeration = "ProofKind", tag = "2")]
    pub proof_dest: i32,
    #[prost(message, optional, tag = "3")]
    pub wrap_timeout: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WrapResponse {
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<Proof>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteRequest {
    #[prost(string, tag = "1")]
    pub hash_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub input: ::core::option::Option<InputKind>,
    #[prost(message, optional, tag = "3")]
    pub execute_timeout: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "4")]
    pub hints: ::core::option::Option<InputKind>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExecuteResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<ExecutionStats>,
    #[prost(bytes = "vec", tag = "2")]
    pub public_outputs: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobKindResponse {
    #[prost(oneof = "job_kind_response::Kind", tags = "1, 2, 3, 4")]
    pub kind: ::core::option::Option<job_kind_response::Kind>,
}
/// Nested message and enum types in `JobKindResponse`.
pub mod job_kind_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Setup(super::SetupResponse),
        #[prost(message, tag = "2")]
        Prove(super::ProveResponse),
        #[prost(message, tag = "3")]
        Wrap(super::WrapResponse),
        #[prost(message, tag = "4")]
        Execute(super::ExecuteResponse),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WaitJobResultRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// server-side hold duration; min 1s, default 5s
    #[prost(uint32, optional, tag = "2")]
    pub timeout_seconds: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WaitJobResultResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub job_status: ::core::option::Option<JobStatus>,
    /// present when job_status is Completed
    #[prost(message, optional, tag = "3")]
    pub result: ::core::option::Option<JobKindResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatus {
    #[prost(oneof = "job_status::Status", tags = "1, 2, 3, 4, 5, 6")]
    pub status: ::core::option::Option<job_status::Status>,
}
/// Nested message and enum types in `JobStatus`.
pub mod job_status {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Status {
        #[prost(message, tag = "1")]
        Queued(super::JobStatusQueued),
        #[prost(message, tag = "2")]
        Running(super::JobStatusRunning),
        #[prost(message, tag = "3")]
        WaitingForInput(super::JobStatusWaitingForInput),
        #[prost(message, tag = "4")]
        Completed(super::JobStatusCompleted),
        #[prost(message, tag = "5")]
        Failed(super::JobStatusFailed),
        #[prost(message, tag = "6")]
        Cancelled(super::JobStatusCancelled),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusQueued {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusRunning {
    #[prost(enumeration = "JobPhase", optional, tag = "1")]
    pub phase: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusWaitingForInput {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusCompleted {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusFailed {
    #[prost(message, optional, tag = "1")]
    pub failure: ::core::option::Option<JobFailure>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobStatusCancelled {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchJobRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEvent {
    #[prost(oneof = "job_event::Event", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub event: ::core::option::Option<job_event::Event>,
}
/// Nested message and enum types in `JobEvent`.
pub mod job_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Queued(super::JobEventQueued),
        #[prost(message, tag = "2")]
        Started(super::JobEventStarted),
        #[prost(message, tag = "3")]
        Progress(super::JobEventProgress),
        #[prost(message, tag = "4")]
        WaitingForInput(super::JobEventWaitingForInput),
        #[prost(message, tag = "5")]
        Completed(super::JobEventCompleted),
        #[prost(message, tag = "6")]
        Cancelled(super::JobEventCancelled),
        #[prost(message, tag = "7")]
        Failed(super::JobEventFailed),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventQueued {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventStarted {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventProgress {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "JobPhase", tag = "2")]
    pub phase: i32,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventWaitingForInput {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventCompleted {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<JobKindResponse>,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventCancelled {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct JobEventFailed {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub failure: ::core::option::Option<JobFailure>,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushJobInputRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub chunk: ::core::option::Option<InputChunk>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PushJobHintsInputRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub chunk: ::core::option::Option<InputChunk>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelJobRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelJobResponse {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    /// true if cancelled; false if already terminal
    #[prost(bool, tag = "2")]
    pub cancelled: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProofKind {
    Unspecified = 0,
    Stark = 1,
    StarkMinimal = 2,
    Plonk = 3,
}
impl ProofKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROOF_KIND_UNSPECIFIED",
            Self::Stark => "PROOF_KIND_STARK",
            Self::StarkMinimal => "PROOF_KIND_STARK_MINIMAL",
            Self::Plonk => "PROOF_KIND_PLONK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROOF_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "PROOF_KIND_STARK" => Some(Self::Stark),
            "PROOF_KIND_STARK_MINIMAL" => Some(Self::StarkMinimal),
            "PROOF_KIND_PLONK" => Some(Self::Plonk),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JobPhase {
    Unspecified = 0,
    /// witness generation and partial contributions
    Contributions = 1,
    /// proof generation
    Prove = 2,
    /// proof aggregation
    Aggregate = 3,
}
impl JobPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "JOB_PHASE_UNSPECIFIED",
            Self::Contributions => "JOB_PHASE_CONTRIBUTIONS",
            Self::Prove => "JOB_PHASE_PROVE",
            Self::Aggregate => "JOB_PHASE_AGGREGATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOB_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "JOB_PHASE_CONTRIBUTIONS" => Some(Self::Contributions),
            "JOB_PHASE_PROVE" => Some(Self::Prove),
            "JOB_PHASE_AGGREGATE" => Some(Self::Aggregate),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod zisk_coordinator_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ZiskCoordinatorApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ZiskCoordinatorApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ZiskCoordinatorApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ZiskCoordinatorApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ZiskCoordinatorApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Register a new guest program. Idempotent: the same ELF always returns
        /// the same hash_id.
        pub async fn register_guest_program(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterGuestProgramRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterGuestProgramResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/RegisterGuestProgram",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.coordinator.v1.ZiskCoordinatorApi",
                        "RegisterGuestProgram",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Submit a new job (setup, prove, wrap, or execute).
        pub async fn job_request(
            &mut self,
            request: impl tonic::IntoRequest<super::JobRequestMessage>,
        ) -> std::result::Result<tonic::Response<super::JobResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/JobRequest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.coordinator.v1.ZiskCoordinatorApi",
                        "JobRequest",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Long-poll: block until the job reaches a terminal state or the server-side
        /// timeout elapses, then return the current status. Loop on this to poll to
        /// completion without application-level sleep.
        pub async fn wait_job_result(
            &mut self,
            request: impl tonic::IntoRequest<super::WaitJobResultRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WaitJobResultResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/WaitJobResult",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.coordinator.v1.ZiskCoordinatorApi",
                        "WaitJobResult",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to live state-transition events for a job. The stream closes
        /// after the terminal event. Safe to call after the job has already finished.
        pub async fn watch_job(
            &mut self,
            request: impl tonic::IntoRequest<super::WatchJobRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::JobEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/WatchJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zisk.coordinator.v1.ZiskCoordinatorApi", "WatchJob"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream additional input chunks to a running job.
        /// Close the stream to signal end-of-input (EOF).
        pub async fn push_job_input(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::PushJobInputRequest,
            >,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/PushJobInput",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.coordinator.v1.ZiskCoordinatorApi",
                        "PushJobInput",
                    ),
                );
            self.inner.client_streaming(req, path, codec).await
        }
        /// Stream additional hints chunks to a running job.
        /// Close the stream to signal end-of-hints (EOF).
        pub async fn push_job_hints_input(
            &mut self,
            request: impl tonic::IntoStreamingRequest<
                Message = super::PushJobHintsInputRequest,
            >,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/PushJobHintsInput",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.coordinator.v1.ZiskCoordinatorApi",
                        "PushJobHintsInput",
                    ),
                );
            self.inner.client_streaming(req, path, codec).await
        }
        /// Cancel a running or queued job. Blocks until the job reaches a terminal
        /// state (Cancelled or another terminal if it completed first).
        /// Idempotent: returns cancelled=false if the job is already in a terminal state.
        pub async fn cancel_job(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelJobRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CancelJobResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.coordinator.v1.ZiskCoordinatorApi/CancelJob",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.coordinator.v1.ZiskCoordinatorApi",
                        "CancelJob",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
