[package]
name = "ere-sp1"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sp1-sdk = "4.2.0"
zkvm-interface = { workspace = true }
toml = "0.8"
tempfile = "3.3"
bincode = "1.3"
thiserror = "2"
tracing = "0.1"
indexmap = { version = "2.9.0", features = ["serde"] }

[lib]
name = "ere_succinct"
path = "src/lib.rs"
