//! ACT4 ELF generation, delegated to a zkevm-test-monitor checkout.

use std::{
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use anyhow::{Context, bail};
use ere_dockerized::zkVMKind;
use serde::{Deserialize, Serialize};

/// ELFs generated by `./run elfs <zkvm>`, laid out as `{elf_dir}/{native,target}/**/*.elf`.
#[derive(Debug, Serialize, Deserialize)]
pub struct Elfs {
    pub zkvm: String,
    pub elf_dir: PathBuf,
    pub act4_commit: String,
    pub act4_version: String,
    pub native: usize,
    pub target: usize,
}

/// Runs `./run elfs <zkvm>` in the monitor checkout, which reports progress on
/// stderr and prints exactly one JSON line on stdout.
pub fn generate(monitor_path: &Path, zkvm_kind: zkVMKind, force: bool) -> anyhow::Result<Elfs> {
    let mut cmd = Command::new("./run");
    cmd.current_dir(monitor_path)
        .args(["elfs", zkvm_kind.as_str()])
        .stderr(Stdio::inherit());
    if force {
        cmd.arg("--force");
    }

    let output = cmd
        .output()
        .with_context(|| format!("failed to run `./run elfs` in {}", monitor_path.display()))?;
    if !output.status.success() {
        bail!("`./run elfs {zkvm_kind}` failed with {}", output.status);
    }

    let stdout = String::from_utf8(output.stdout).context("`./run elfs` printed non-UTF-8")?;
    let line = stdout
        .lines()
        .last()
        .context("`./run elfs` printed nothing")?;
    serde_json::from_str(line).with_context(|| format!("unexpected `./run elfs` output: {line}"))
}
