//! `ere-conformance` runs the ACT4 RISC-V architectural test suite against the
//! `ere-server-*` images published for an ere revision, and records the results
//! for the conformance dashboard.
//!
//! Test ELFs are generated by a [zkevm-test-monitor] checkout (`./run elfs`).
//!
//! [zkevm-test-monitor]: https://github.com/eth-act/zkevm-test-monitor

use std::path::PathBuf;

use anyhow::Error;
use clap::{Parser, Subcommand};
use ere_dockerized::zkVMKind;
use tracing_subscriber::EnvFilter;

mod elfs;
mod provenance;
mod record;
mod run;

#[derive(Parser)]
#[command(author, version, about)]
struct Args {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Generate ACT4 ELFs with a zkevm-test-monitor checkout.
    Elfs {
        /// zkVMs to generate ELFs for.
        #[arg(long, value_delimiter = ',', default_values = ["openvm", "sp1", "zisk"])]
        zkvm: Vec<zkVMKind>,
        /// Path to a zkevm-test-monitor checkout.
        #[arg(long, env = "ERE_MONITOR_PATH")]
        monitor_path: PathBuf,
        /// Regenerate ELFs even if they already exist.
        #[arg(long)]
        force: bool,
    },
    /// Run an ACT4 suite against the images published for an ere revision.
    Run(run::RunArgs),
}

fn main() -> Result<(), Error> {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| EnvFilter::new("ere_conformance=info,warn")),
        )
        .init();

    match Args::parse().command {
        Command::Elfs {
            zkvm,
            monitor_path,
            force,
        } => {
            for zkvm_kind in zkvm {
                let elfs = elfs::generate(&monitor_path, zkvm_kind, force)?;
                println!("{}", serde_json::to_string(&elfs)?);
            }
        }
        Command::Run(args) => run::run(args)?,
    }

    Ok(())
}
