[package]
name = "ere-compile-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cargo_metadata.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints]
workspace = true
