[package]
name = "ere-pico"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zkvm-interface = { workspace = true }
thiserror = "2"
pico-sdk = { git = "https://github.com/brevis-network/pico", tag = "v1.1.3" }
bincode = "1.3.3"

[lints]
workspace = true
