// This file is @generated by prost-build.
/// Standardized error response
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorResponse {
    /// Error code
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    /// Human-readable error message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemStatusRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemStatusResponse {
    #[prost(oneof = "system_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<system_status_response::Result>,
}
/// Nested message and enum types in `SystemStatusResponse`.
pub mod system_status_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Status(super::SystemStatus),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SystemStatus {
    #[prost(uint32, tag = "1")]
    pub total_workers: u32,
    #[prost(uint32, tag = "2")]
    pub compute_capacity: u32,
    #[prost(uint32, tag = "3")]
    pub idle_workers: u32,
    #[prost(uint32, tag = "4")]
    pub busy_workers: u32,
    #[prost(uint32, tag = "5")]
    pub active_jobs: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LaunchProofRequest {
    #[prost(string, tag = "1")]
    pub data_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub compute_capacity: u32,
    #[prost(uint32, tag = "3")]
    pub minimal_compute_capacity: u32,
    #[prost(enumeration = "InputMode", tag = "4")]
    pub inputs_mode: i32,
    #[prost(string, optional, tag = "5")]
    pub inputs_uri: ::core::option::Option<::prost::alloc::string::String>,
    /// Input data sent directly from client
    #[prost(bytes = "vec", optional, tag = "6")]
    pub input_data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(enumeration = "HintsMode", tag = "7")]
    pub hints_mode: i32,
    #[prost(string, optional, tag = "8")]
    pub hints_uri: ::core::option::Option<::prost::alloc::string::String>,
    /// If set, indicates this is a simulated worker
    #[prost(uint32, optional, tag = "9")]
    pub simulated_node: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LaunchProofResponse {
    #[prost(oneof = "launch_proof_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<launch_proof_response::Result>,
}
/// Nested message and enum types in `LaunchProofResponse`.
pub mod launch_proof_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Result {
        #[prost(string, tag = "1")]
        JobId(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Error(super::ErrorResponse),
    }
}
/// Subscription request message
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeToProofRequest {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
}
/// Subscription status update (streamed to client)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProofStatusUpdate {
    #[prost(string, tag = "1")]
    pub job_id: ::prost::alloc::string::String,
    #[prost(enumeration = "ProofStatusType", tag = "2")]
    pub status: i32,
    /// Present on success
    #[prost(message, optional, tag = "3")]
    pub final_proof: ::core::option::Option<FinalProof>,
    /// Present on failure
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<ErrorResponse>,
    #[prost(uint64, tag = "5")]
    pub duration_ms: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FinalProof {
    #[prost(uint64, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag = "2")]
    pub executed_steps: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InputMode {
    /// No input provided
    None = 0,
    /// Input will be provided as a PATH
    Path = 1,
    /// Input data will be sent directly
    Data = 2,
}
impl InputMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "INPUT_MODE_NONE",
            Self::Path => "INPUT_MODE_PATH",
            Self::Data => "INPUT_MODE_DATA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INPUT_MODE_NONE" => Some(Self::None),
            "INPUT_MODE_PATH" => Some(Self::Path),
            "INPUT_MODE_DATA" => Some(Self::Data),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HintsMode {
    /// No hints provided
    None = 0,
    /// Hints will be provided as a PATH
    Path = 1,
    /// Hints will be sent as a stream
    Stream = 2,
}
impl HintsMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "HINTS_MODE_NONE",
            Self::Path => "HINTS_MODE_PATH",
            Self::Stream => "HINTS_MODE_STREAM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HINTS_MODE_NONE" => Some(Self::None),
            "HINTS_MODE_PATH" => Some(Self::Path),
            "HINTS_MODE_STREAM" => Some(Self::Stream),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProofStatusType {
    ProofStatusCompleted = 0,
    ProofStatusFailed = 1,
}
impl ProofStatusType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ProofStatusCompleted => "PROOF_STATUS_COMPLETED",
            Self::ProofStatusFailed => "PROOF_STATUS_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROOF_STATUS_COMPLETED" => Some(Self::ProofStatusCompleted),
            "PROOF_STATUS_FAILED" => Some(Self::ProofStatusFailed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod zisk_distributed_api_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ZiskDistributedApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ZiskDistributedApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ZiskDistributedApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ZiskDistributedApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ZiskDistributedApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// System status
        pub async fn system_status(
            &mut self,
            request: impl tonic::IntoRequest<super::SystemStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SystemStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/SystemStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "SystemStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Launch a proof job
        pub async fn launch_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::LaunchProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LaunchProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/LaunchProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "LaunchProof",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Client subscription to job completion
        pub async fn subscribe_to_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeToProofRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ProofStatusUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zisk.distributed.api.v1.ZiskDistributedApi/SubscribeToProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zisk.distributed.api.v1.ZiskDistributedApi",
                        "SubscribeToProof",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
