name: Check Pico Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_pico_image:
    if: ${{ false }} # See issue #49
    name: Build Pico Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dependent Docker base image
        run: |
          docker build \
            --file docker/base/Dockerfile.base \
            --tag ere-base:latest \
            .

      - name: Build Pico Docker image
        run: |
          docker build \
            --file docker/pico/Dockerfile \
            --tag ere-builder-pico-check:latest \
            .