name: Check ZisK Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_zisk_image:
    name: Build ZisK Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dependent Docker base image
        run: |
          docker build \
            --file docker/base/Dockerfile.base \
            --tag ere-base:latest \
            .

      - name: Build ZisK Docker image
        run: |
          docker build \
            --file docker/zisk/Dockerfile \
            --tag ere-builder-zisk-check:latest \
            .