name: Test and clippy ZKM

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test-zkvm.yml
    permissions:
      contents: read
      packages: write
    with:
      zkvm: zkm
      toolchain: 1.86.0
      test_ere_dockerized: false
      test_options: 'execute compile'
