[package]
name = "ere-zkm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zkm-sdk = { git = "https://github.com/zkMIPS/zkMIPS.git", tag = "v1.1.0" }
zkvm-interface = { workspace = true }
toml = "0.8"
tempfile = "3.3"
bincode = "1.3"
thiserror = "2"
tracing = "0.1"
indexmap = { version = "2.9.0", features = ["serde"] }


[lints]
workspace = true
